### PR TITLE
Squash diet goal bugs found by nihalzp

### LINKED ISSUE #321: edit-diet-goal not throwing when none of the arguments are present
image

From UG: `**Note: At least one of the nutrients (CALORIES,PROTEIN,CARB,FATS) must be present!**`

### LINKED ISSUE #323: Editing weekly calorie value changes the daily goal as well
image

### LINKED ISSUE #325: Diet goal reads the protein value from diet for calories
image

### PR DESCRIPTION
**Pull request by yicheng-toh**
Squash diet goal bugs found by nihalzp
Fixes #321 
Fixes #323 
Fixes #325

### CODE REVIEW

File: src/main/java/athleticli/parser/DietParser.java [hunk 1]
```diff
@@ -92,6 +92,9 @@ private static ArrayList<DietGoal> createNewDietGoals(int nutrientStartingIndex,
             dietGoals.add(dietGoal);
             recordedNutrients.add(nutrient);
         }
+        if(dietGoals.isEmpty()){
```
Comment (skylee03) [inline src/main/java/athleticli/parser/DietParser.java:95]:
```suggestion
        if (dietGoals.isEmpty()) {
```

File: src/main/java/athleticli/commands/diet/EditDietGoalCommand.java [hunk 2]
```diff
@@ -50,7 +50,14 @@ private void updateUserGoals(DietGoalList currentDietGoals) {
...
             for (DietGoal currentDietGoal : currentDietGoals) {
-                if (!userUpdatedDietGoal.getNutrient().equals(currentDietGoal.getNutrient())) {
+                boolean isSameDietGoalNutrient =
+                        userUpdatedDietGoal.getNutrient().equals(currentDietGoal.getNutrient());
+                boolean isSameTimeSpan = userUpdatedDietGoal.getTimeSpan().getDays()
+                        == currentDietGoal.getTimeSpan().getDays();
+                if (!isSameDietGoalNutrient) {
+                    continue;
+                }
+                if (!isSameTimeSpan){
```
Comment (skylee03) [inline src/main/java/athleticli/commands/diet/EditDietGoalCommand.java:60]:
```suggestion
                if (!isSameTimeSpan) {
```

**Review by skylee03 — APPROVED** [review]
LGTM!
