### PR TITLE
Bug fixes for diet goals

### LINKED ISSUE #52: Stop AthletiCLI from crashing when only the diet goal command is given
It will crash when only the command is given since it requires other arguments.

### PR DESCRIPTION
**Pull request by yicheng-toh**
Fixes #52 , #53

### CODE REVIEW

File: src/main/java/athleticli/ui/Parser.java [hunk 1]
```diff
@@ -555,7 +557,9 @@ public static EditSleepCommand parseSleepEdit(String commandArgs) throws Athleti
      * @throws AthletiException Invalid input by the user.
      */
     public static ArrayList<DietGoal> parseDietGoalSetEdit(String commandArgs) throws AthletiException {
-        System.out.println(commandArgs);
+        if (commandArgs.isEmpty()){
```
Comment (skylee03) [inline src/main/java/athleticli/ui/Parser.java:560]:
```suggestion
        if (commandArgs.isEmpty()) {
```

File: src/main/java/athleticli/ui/Parser.java [hunk 2]
```diff
@@ -579,8 +584,12 @@ public static ArrayList<DietGoal> parseDietGoalSetEdit(String commandArgs) throw
                 if (!verifyValidNutrients(nutrient)) {
                     throw new AthletiException(Message.MESSAGE_DIETGOAL_INVALID_NUTRIENT);
                 }
+                if (recordedNutrients.contains(nutrient)){
```
Comment (skylee03) [inline src/main/java/athleticli/ui/Parser.java:587]:
```suggestion
                if (recordedNutrients.contains(nutrient)) {
```

**Review by skylee03 — APPROVED** [review]
LGTM!
